# Generated by Django 3.0.3 on 2020-09-27 10:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200927_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 27, 10, 51, 18, 95085, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 27, 10, 51, 18, 95085, tzinfo=utc)),
        ),
    ]
