# Generated by Django 3.0.3 on 2022-09-04 16:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220904_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_picture',
            field=models.ImageField(null=True, upload_to='post_pic/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 4, 16, 36, 20, 394867, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 4, 16, 36, 20, 394867, tzinfo=utc)),
        ),
    ]
