# Generated by Django 3.0.3 on 2022-09-05 05:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220904_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 5, 5, 4, 29, 185627, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 5, 5, 4, 29, 185627, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='PostView',
        ),
    ]
