# Generated by Django 3.0.3 on 2020-09-28 05:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200927_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpicture',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default='2020-07-06'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 28, 5, 48, 40, 385780, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 28, 5, 48, 40, 385780, tzinfo=utc)),
        ),
    ]
