# Generated by Django 3.0.3 on 2022-09-05 07:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20220905_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='is_subscribed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 5, 7, 19, 12, 33253, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 5, 7, 19, 12, 33253, tzinfo=utc)),
        ),
    ]
